{
 "title": "Rust vs Go",
 "tags": [ "benchmark" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "IO (packets/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    { "expr": "rate(rust_packets_total[10s])", "legendFormat": "Rust IO" },
    { "expr": "rate(go_packets_total[10s])", "legendFormat": "Go IO" }
   ]
  },
  {
   "title": "Memory (RSS bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job='rust'}",
     "legendFormat": "Rust RAM (RSS)"
    },
    {
     "expr": "process_resident_memory_bytes{job='go'}",
     "legendFormat": "Go RAM (RSS)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job='rust'}[10s]) * 100",
     "legendFormat": "Rust CPU %"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job='go'}[10s]) * 100",
     "legendFormat": "Go CPU %"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "process_threads{job='rust'}", "legendFormat": "Rust Threads" },
    { "expr": "go_threads{job='go'}", "legendFormat": "Go Threads" }
   ]
  }
 ]
}